---
- name: Provision main machine
  hosts: localhost
  remote_user: "{{ lookup('env','USER') }}"
  become: yes

  roles:
    - { role: package-managers, tags: package }
    - { role: keyboard-basics, tags: keyboard }
    - { role: copypaste, tags: copypaste }
    - { role: terminal, tags: terminal }
    - { role: dev-tools, tags: dev }
    - { role: devops, tags: devops }
    - { role: auth, tags: auth }
    - { role: net, tags: net }
    - { role: browser, tags: browse }
    - { role: messaging, tags: msg }
    - { role: container, tags: container }
    - { role: hosting, tags: hosting }
    - { role: virtualbox, tags: virtualbox }
    - { role: iot, tags: iot }
