---
- name: Provision main machine
  hosts: localhost
  remote_user: "{{ lookup('env','USER') }}"
  become: yes

  roles:
    - { role: hosting, tags: hosting }
    - { role: dev-tools, tags: dev }
    - { role: devops, tags: devops }
    - { role: container, tags: container }
