---
- name: Install Docker
  apt: name=docker.io

- name: Create Docker group
  group:
    name: docker

- name: Add current user to Docker group
  user:
    name: "{{lookup('env', 'USER')}}"
    append: yes
    groups: docker

- name: Apply group changes for Docker, pre-relog
  command: newgrp docker
  become: no

- debug:
    msg: Don't forget to relog to let the new user group take effect.

- name: Install Docker-Compose
  apt: name=docker-compose

- name: Install https transport package for apt, recommended for kubectl
  apt: name=apt-transport-https

- name: Add apt key for kubectl
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add kubectl repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: Install kubectl for Kubernetes
  apt: name=kubectl

- name: Install Helm client
  command: snap install helm --classic
