---
- name: Install xterm
  apt: name=xterm

- name: Install tmux
  apt: name=tmux

- name: Ensure tmux plugin dir
  become: no
  file:
    path: ~/.config/tmux/plugins
    state: directory

- name: Install tmux plugin manager
  become: no
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.config/tmux/plugins/tpm
    force: yes

- name: Run tmux plugin manager install script
  become: no
  command: ~/.config/tmux/plugins/tpm/bin/install_plugins

- name: Install xclip, for copy-pasting
  apt: name=xclip

- name: Install Powerline, for fancier tmux feedback
  apt: name=powerline

- name: Install Powerline fonts, for fancier tmux feedback
  apt: name=fonts-powerline

- name: Install Midnight Commander
  apt: name=mc

- name: Install AutoJump, for easy dir access
  apt: name=autojump

- name: Install SilverSearcher, for easy file finding
  apt: name=silversearcher-ag

- name: Install bat, a cat alternative
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.11.0/bat-musl_0.11.0_amd64.deb

- name: Install exa, an ls alternative
  apt: name=exa

- name: Install htop, an alternative to top
  apt: name=htop
