---
- name: Install Gnome Tweak Tool (to enable Compose Key)
  apt: name=gnome-tweak-tool state=present

- name: Configure Compose Key
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS='
    line: XKBOPTIONS=compose:ralt

- name: Reinitialize console setup after configuring Compose Key
  command: dpkg-reconfigure -f noninteractive console-setup

- name: Configure xmodmap prefs to set Compose Key 1/2
  lineinfile:
    path: ~/.Xmodmap
    regexp: '^keycode 108'
    line: keycode 108 = Alt_R
    create: yes
  become: no

- name: Configure xmodmap prefs to set Compose Key 2/2
  lineinfile:
    path: ~/.Xmodmap
    regexp: '^keysym Alt_R'
    line: keysym Alt_R = Multi_key
    create: yes
  become: no

- name: Create Gnome extensions dir [Emoji Selector]
  file:
    path: ~/.local/share/gnome-shell/extensions/emoji-selector@maestrochan.fr
    state: directory
  become: no

- name: Download and unpack Gnome extension [Emoji Selector]
  unarchive:
    src: https://extensions.gnome.org/extension-data/emoji-selectormaestroschan.fr.v15.shell-extension.zip
    dest: ~/.local/share/gnome-shell/extensions/emoji-selector@maestrochan.fr
    remote_src: yes
  become: no

- name: Enable Gnome extension [Emoji Selector]
  command: gnome-shell-extension-tool -e emoji-selector@maestrochan.fr
  ignore_errors: yes
  become: no

- name: Reload Gnome extension [Emoji Selector]
  command: gnome-shell-extension-tool -r emoji-selector@maestrochan.fr
  become: no
