---
- name: Install Git client
  apt: name=git

- name: Install NeoVim
  apt: name=neovim

- name: Install PHP 7 CLI
  apt: name=php-cli

- name: Install Vim plugins
  command: vim -c ':PlugInstall | quit | quit'
  become: no

- name: Install CMake, for Vim plugin compilation
  apt: name=cmake

- name: Install build-essential, for YouCompleteMe deps and others
  apt: name=build-essential

- name: Install Python dev, for YouCompleteMe deps and others
  apt: name=python-dev

- name: Install setuptools, for YouCompleteMe deps and others
  apt: name=python3-setuptools

- name: Install Python Vim bindings, for YouCompleteMe deps and others
  pip:
    name: pynvim
    extra_args: --user
  become: no

- name: Install PHP Composer
  apt: name=composer

- name: Install Python3 apt support
  apt: name=python3-apt

- name: Install latest npm, for compatibility with nodejs v10
  npm:
    name: npm
    global: yes
    state: latest

- name: Install Yarn
  npm:
    name: yarn
    global: yes
    state: latest

- name: Install Gulp
  apt: name=gulp

- name: Install Homebrew installer script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
    dest: /tmp/
    mode: '0700'
  become: no

- name: Run Homebrew installer
  command: /tmp/install.sh
  become: no
