---
- name: Install Git client
  apt: name=git

- name: Install NeoVim
  apt: name=neovim

- name: Install ripgrep, for Notational Velocity's fast regex dir searching
  apt: name=ripgrep

- name: Install fzf, fuzzy file finder, needed by Notational Velocity
  apt: name=fzf

- name: Install Vim plugins
  command: vim -c ':PlugInstall | quit | quit'
  become: no

- name: Install CMake, for Vim plugin compilation
  apt: name=cmake

- name: Install YouCompleteMe (Vim plugin) deps
  become: no
  command: python3 install.py
  args:
    chdir: ~/.vim/plugged/YouCompleteMe

- name: Install PHP Composer
  apt: name=composer

- name: Install Travis CI client
  apt: name=travis

- name: Install Python3 apt support
  apt: name=python3-apt

- name: Install Todoist API
  pip:
    name: todoist-python
    extra_args: --user
  become: no

- name: Install nodejs version switcher
  npm:
    name: n
    global: yes

- name: Install latest npm, for compatibility with nodejs v10
  npm:
    name: npm
    global: yes
    state: latest

- name: Install Java runtime (Katalon Studio needs OpenJDK 8)
  apt: name=openjdk-8-jre
