---
# Git
- name: Install Git client
  apt: name=git

# Coding langs
- name: Install PHP 7 CLI
  apt: name=php-cli

- name: Install Python dev, for YouCompleteMe deps and others
  apt: name=python-dev

- name: Install setuptools, for YouCompleteMe deps and others
  apt: name=python3-setuptools

- name: Install Python Vim bindings, for YouCompleteMe deps and others
  pip:
    name: pynvim
    extra_args: --user
  become: no

# Compilers
- name: Install CMake, for Vim plugin compilation
  apt: name=cmake

- name: Install build-essential, for YouCompleteMe deps and others
  apt: name=build-essential

# Package managers
- name: Install PHP Composer
  apt: name=composer

- name: Install latest npm, for compatibility with nodejs v10
  npm:
    name: npm
    global: yes
    state: latest

- name: Install Yarn
  npm:
    name: yarn
    global: yes
    state: latest

- name: Install Python3 apt support
  apt: name=python3-apt

- name: Install Homebrew installer script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
    dest: /tmp/
    mode: '0700'
  become: no

- name: Run Homebrew installer
  command: /tmp/install.sh
  become: no

# Runners
- name: Install Gulp
  apt: name=gulp

# Editors
- name: Install NeoVim
  apt: name=neovim

- name: Install Vim plugins
  command: vim -c ':PlugInstall | quit | quit'
  become: no

# Emacs
- name: Install Emacs 27
  snap:
    name: emacs
    classic: yes
    channel: beta

# Doom dependencies
- name: Install fd-find
  apt: name=fd-find
- name: Install Git
  apt: name=git
- name: Install ripgrep
  apt: name=ripgrep

- name: Check if Doom was already installed
  stat:
    path: ~/.emacs.d/bin/doom
  register: doom_bin_file
  become: no

- name: Clone Doom repo, if Doom is not installed
  git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: ~/.emacs.d
    depth: 0
  when: not doom_bin_file.stat.exists
  become: no

- name: Run the Doom installer, if Doom is not installed
  command: ~/.emacs.d/bin/doom
  when: not doom_bin_file.stat.exists
  become: no
