---
- name: Provision main machine
  hosts: localhost
  remote_user: "{{ lookup('env','USER') }}"
  become: yes

  roles:
    - { role: keyboard-basics, tags: keyboard }
    - { role: terminal, tags: terminal }
    - { role: power-saving }
    - { role: dev-tools, tags: dev }
    - { role: auth, tags: auth }
    - { role: media, tags: media }
    - { role: net, tags: net }
    - { role: browser, tags: browse }
    - { role: messaging, tags: msg }
    - { role: file-sync, tags: sync }
    - { role: virtualbox }
