---
- name: Install Git client
  apt: name=git

- name: Install NeoVim
  apt: name=neovim

- name: Install ripgrep, for Notational Velocity's fast regex dir searching
  apt: name=ripgrep

- name: Install fzf, fuzzy file finder, needed by Notational Velocity
  apt: name=fzf
